### ISSUE TITLE
Copyright and License violation

### ISSUE THREAD

**Issue by haojunsui** [ijry/lyicon#2]
This project is using code copied from:
https://github.com/FortAwesome/Font-Awesome
but copyright and license terms were altered and reclaimed.
Please immediately delete all the copied code or adapt it to conform the original copyright and license requirements.

Please carefully read the license and act promptly.

I will also contact the original author (@FortAwesome) of violating package here.

**Comment by ijry** [comment]
we have removed docs from https://github.com/FortAwesome/Font-Awesome, thks.
